import { useState } from 'react';
import { Box, Button, TextField, Typography, Stack, Grid } from '@mui/material';
import { useTranslation } from 'react-i18next';

interface Step3InvoiceDataProps {
  initialValues?: {
    invoiceNumber?: string;
    settlementNumber?: string;
    irpfPercentage?: number;
    rePercentage?: number;
    notes?: string;
  };
  onNext: (data: {
    invoiceNumber: string;
    settlementNumber?: string;
    irpfPercentage?: number;
    rePercentage?: number;
    notes?: string;
  }) => void;
  onBack: () => void;
}

export const Step3InvoiceData: React.FC<Step3InvoiceDataProps> = ({
  initialValues,
  onNext,
  onBack,
}) => {

  const { t } = useTranslation(['invoices', 'common']);

  const [formData, setFormData] = useState({
    invoiceNumber: initialValues?.invoiceNumber || '',
    settlementNumber: initialValues?.settlementNumber || '',
    irpfPercentage: initialValues?.irpfPercentage ?? 0,
    rePercentage: initialValues?.rePercentage ?? 0,
    notes: initialValues?.notes || '',
  });

  const [errors, setErrors] = useState<{ [key: string]: string }>({});

  const validate = () => {
    const newErrors: { [key: string]: string } = {};

    // Invoice number is auto-generated by backend, so we don't validate it here
    // if (!formData.invoiceNumber.trim()) {
    //   newErrors.invoiceNumber = t('invoices:wizard.step3.errors.invoiceNumberRequired');
    // } else if (!/^[A-Za-z0-9./-]+$/.test(formData.invoiceNumber)) {
    //   newErrors.invoiceNumber = t('invoices:wizard.step3.errors.invoiceNumberInvalid');
    // }

    if (formData.irpfPercentage < 0 || formData.irpfPercentage > 100) {
      newErrors.irpfPercentage = t('invoices:wizard.step3.errors.irpfRange');
    }

    if (formData.rePercentage < 0 || formData.rePercentage > 100) {
      newErrors.rePercentage = t('invoices:wizard.step3.errors.reRange');
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleNext = () => {
    if (validate()) {
      // El backend genera automáticamente issueDate con la fecha actual
      onNext(formData);
    }
  };

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  return (
    <Box>
      <Typography variant="h6" gutterBottom>
        {t('invoices:wizard.step3.title')}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        {t('invoices:wizard.step3.subtitle')}
      </Typography>

      <Grid container spacing={6}>
        <Grid item xs={12} sm={6}>
          <TextField
            fullWidth
            disabled
            label={t('invoices:wizard.step3.invoiceNumber')}
            value={t('invoices:wizard.step3.autoGenerated')}
            helperText={t('invoices:wizard.step3.autoGeneratedHelper')}
          />
        </Grid>

        <Grid item xs={12} sm={6}>
          <TextField
            fullWidth
            label={t('invoices:wizard.step3.settlementNumber')}
            value={formData.settlementNumber}
            onChange={(e) => handleChange('settlementNumber', e.target.value)}
            helperText={t('invoices:wizard.step3.settlementNumberHelper')}
            placeholder="LIQ-001"
          />
        </Grid>

        <Grid item xs={12} sm={4}>
          <TextField
            fullWidth
            type="number"
            label={t('invoices:wizard.step3.irpf')}
            value={formData.irpfPercentage}
            onChange={(e) => handleChange('irpfPercentage', e.target.value)}
            error={!!errors.irpfPercentage}
            helperText={errors.irpfPercentage || t('invoices:wizard.step3.irpfHelper')}
            inputProps={{ min: 0, max: 100, step: 0.01 }}
          />
        </Grid>

        <Grid item xs={12} sm={4}>
          <TextField
            fullWidth
            type="number"
            label={t('invoices:wizard.step3.re')}
            value={formData.rePercentage}
            onChange={(e) => handleChange('rePercentage', e.target.value)}
            error={!!errors.rePercentage}
            helperText={errors.rePercentage || t('invoices:wizard.step3.reHelper')}
            inputProps={{ min: 0, max: 100, step: 0.01 }}
          />
        </Grid>

        <Grid item xs={12} sm={4}>
          <TextField
            fullWidth
            label={t('invoices:wizard.step3.notes')}
            value={formData.notes}
            onChange={(e) => handleChange('notes', e.target.value)}
            helperText={t('invoices:wizard.step3.notesHelper')}
            multiline
          />
        </Grid>
      </Grid>

      <Stack direction="row" spacing={2} sx={{ mt: 4 }}>
        <Button variant="outlined" onClick={onBack}>
          {t('common:actions.back')}
        </Button>
        <Button variant="contained" onClick={handleNext}>
          {t('common:actions.next', 'Siguiente')}
        </Button>
      </Stack>
    </Box>
  );
};
